apiVersion: v1
kind: Service
metadata:
  name: pyhealthchecker
  namespace: pyhealthchecker
spec:
  selector:
    app: pyhealthchecker
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort